### ISSUE TITLE
risk_control如何获取

### ISSUE THREAD

**Issue by wwqhy** [johncyuan/jd-assistant#1]

**Comment by wwqhy** [comment]
config.ini提到的risk_control如何获取?谢谢
在html里发现有，但是未赋值

**Comment by johncyuan** [comment]
如果是像某酒那种模式这个参数可以随便填或者注释掉判断（至少现在没有用到），其他模式没测试以前可以获取到现在获取不到了，可能已经改了逻辑

**Comment by wwqhy** [comment]
> 如果是像某酒那种模式这个参数可以随便填或者注释掉判断（至少现在没有用到），其他模式没测试以前可以获取到现在获取不到了，可能已经改了逻辑

收到，您这边留个联系方式吧，私聊

**Comment by johncyuan** [comment]
d3hfY3l1YW4=

**Comment by wwqhy** [comment]
> d3hfY3l1YW4=

?

**Comment by johncyuan** [comment]
微信base64

**Comment by wwqhy** [comment]
> 微信base64

666，发个微信号吧
